name: Docker Demo

on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: | 
        response=$(curl -k -d "user=pixiadmin@demo.mail&pass=adminpixi" -X POST https://photo-demo.westeurope.cloudapp.azure.com/axl/api/user/login | jq -r '.token')
        echo "response from curl= $response"
        
        docker pull 42crunch/scand-agent:v2.0.0
        docker run -e SCAN_TOKEN=scan_e5aab4b8-9c9f-44bd-9a3e-c020224cbbaf -e SCAN42C_SECURITY_ACCESS_TOKEN=$response -e PLATFORM_SERVICE=services.demolabs.42crunch.cloud:8001 42crunch/scand-agent:v2.0.0